### PR TITLE
LPS-146896 WIP Add pre-sort custom view endpoints

### PR DESCRIPTION
**Pull request by mateussgn**
Related issue: https://issues.liferay.com/browse/LPS-146896

### CODE REVIEW

**Comment by mateussgn** [comment]
ci:test:sf

**Comment by mateussgn** [comment]
ci:test:sf

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:reevaluate:1277401_1884

**Comment by danvb112** [comment]
ci:reevaluate:1317401_2285

**Pull request closed without merging**
