### PR TITLE
LPS-158366 Fix upgrade step

### PR DESCRIPTION
**Pull request by mateussgn**
Related issue: https://issues.liferay.com/browse/LPS-158366

### CODE REVIEW

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@mateussgn I merged this to master and the temp branch, please keep an eye out.

**Comment by vicnate5** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
@mateussgn Per the automation results, there is still issues upgrading here

PostgreSQL
```
ERROR [main][UpgradeStepRegistratorTracker:221] Failed upgrade process for module com.liferay.object.service
 com.liferay.portal.kernel.upgrade.UpgradeException: org.postgresql.util.PSQLException: Bad value for type long : t
 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:107) ~[portal-kernel.jar:?]
 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:125) ~[portal-kernel.jar:?]
 	at com.liferay.portal.upgrade.internal.executor.UpgradeExecutor$UpgradeInfosRunnable.run(UpgradeExecutor.java:230) ~[?:?]
 	at com.liferay.portal.output.stream.container.internal.OutputStreamContainerFactoryTrackerImpl.runWithSwappedLog(OutputStreamContainerFactoryTrackerImpl.java:134) [bundleFile:?]
```

SQL Server
```
INFO  [main][UpgradeProcess:113] Failed upgrade process com.liferay.object.internal.upgrade.v3_18_0.ObjectFieldUpgradeProcess in 2 ms
 2022-07-18 23:29:39.200 ERROR [main][ReleaseManagerImpl:190] Failed upgrade process for module com.liferay.object.service
 com.liferay.portal.kernel.upgrade.UpgradeException: com.microsoft.sqlserver.jdbc.SQLServerException: Invalid column name 'true'.
 ```
 
 CC @andreefarias

**Comment by mateussgn** [comment]
ci:test:upgrade

**Comment by mateussgn** [comment]
ci:test:upgrade

**Comment by gabrielwas** [comment]
resent here https://github.com/liferay-objects/liferay-portal/pull/838

**Comment by gabrielwas** [comment]
ci:close

**Pull request closed without merging**
