### PR TITLE
LRQA-66228 Make sure only 2 structures will be retuned

### PR DESCRIPTION
**Pull request by mateussgn**

### CODE REVIEW

**Comment by mateussgn** [comment]
ci:test:backend

**Comment by mateussgn** [comment]
@guilhermedcamacho

**Comment by mateussgn** [comment]
ci:help

**Comment by mateussgn** [comment]
ci:test:sf

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by mateussgn** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Pull request closed without merging**
